//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParamsChannelsEnterprise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdministrationSwitchEntities : DbContext
    {
        public AdministrationSwitchEntities()
            : base("name=AdministrationSwitchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChannelEnterprise> ChannelEnterprise { get; set; }
        public virtual DbSet<Enterprise> Enterprise { get; set; }
        public virtual DbSet<Channel> Channel { get; set; }
        public virtual DbSet<QueryManager> QueryManager { get; set; }
    
        public virtual ObjectResult<ChannelEnterpriseInfo> GetChannel(string channel)
        {
            var channelParameter = channel != null ?
                new ObjectParameter("Channel", channel) :
                new ObjectParameter("Channel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChannelEnterpriseInfo>("GetChannel", channelParameter);
        }
    
        public virtual ObjectResult<QueryInfo> GetQuery(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QueryInfo>("GetQuery", codeParameter);
        }
    }
}
