//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParamsChannelsEnterprise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SwitchAtiscodeEntities : DbContext
    {
        public SwitchAtiscodeEntities()
            : base("name=SwitchAtiscodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtisLogTran> AtisLogTran { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
    
        public virtual int LiberarSecuencial(string canal, string secuencial, string tipo)
        {
            var canalParameter = canal != null ?
                new ObjectParameter("canal", canal) :
                new ObjectParameter("canal", typeof(string));
    
            var secuencialParameter = secuencial != null ?
                new ObjectParameter("secuencial", secuencial) :
                new ObjectParameter("secuencial", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LiberarSecuencial", canalParameter, secuencialParameter, tipoParameter);
        }
    }
}
